name: "Publish Code Coverage Results on Sonar Cloud"
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Install Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build Golang Sources
        run: make

      - name: Publish Sonar Scan Result on SonarCloud.io
        uses: SonarSource/sonarcloud-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}